name: SmartLifts
version: '1.0.1'
description: Lifts to travel between floors, checking paths for configurable interfering blocks and range.


author: EasyMFnE

database: false
main: net.easymfne.smartlifts.SmartLifts
load: POSTWORLD

commands:
  smartlifts:
    description: SmartLifts main command
    permission: smartlifts.command.smartlifts
    permission-message: 'Unknown command. Type "/help" for help.'
    usage: /smartlifts reload - Reload configuration from disk

permissions:
  smartlifts.command.smartlifts:
    description: Allow use of SmartLifts command
    default: op
  smartlifts.lift.make:
    description: Allow creation of Lift signs
    default: op
  smartlifts.lift.use:
    description: Allow usage of Lift signs
    default: true
